apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "demo-helm-chart.fullname" . }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: smb